import TimelineList from "@/components/TimelineList";


export const metadata = {
  title: "Timeline | KeenKeeper",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className=" px-6 py-10">

      <TimelineList />

    </div>
  );
};

export default page;